local locale = {
	["en"] = {
		Month = {
			-- Short
			Jan = "Jan",
			Feb = "Feb",
			Mar = "Mar",
			Apr = "Apr",
			May = "May",
			Jun = "Jun",
			Jul = "Jul",
			Aug = "Aug",
			Sep = "Sep",
			Oct = "Oct",
			Nov = "Nov",
			Dec = "Dec",
			-- Full
			January = "January",
			February = "February",
			March = "March",
			April = "April",
			-- May already defined
			June = "June",
			July = "July",
			August = "August",
			September = "September",
			October = "October",
			November = "November",
			December = "December",
		},
		Day = {
			-- Short
			Mon = "Mon",
			Tue = "Tue",
			Wed = "Wed",
			Thu = "Thu",
			Fri = "Fri",
			Sat = "Sat",
			Sun = "Sun",
			-- Full
			Monday = "Monday",
			Tuesday = "Tuesday",
			Wednesday = "Wednesday",
			Thursday = "Thursday",
			Friday = "Friday",
			Saturday = "Saturday",
			Sunday = "Sunday",
		}
	},
	-- German
	["de"] = {
		Month = {
			-- Short
			Jan = "Jan",
			Feb = "Feb",
			Mar = "Mär",
			Apr = "Apr",
			May = "Mai",
			Jun = "Jun",
			Jul = "Jul",
			Aug = "Aug",
			Sep = "Sep",
			Oct = "Okt",
			Nov = "Nov",
			Dec = "Dez",
			-- Full
			January = "Januar",
			February = "Februar",
			March = "März",
			April = "April",
			-- May already defined
			June = "Juni",
			July = "Juli",
			August = "August",
			September = "September",
			October = "Oktober",
			November = "November",
			December = "Dezember",
		},
		Day = {
			-- Short
			Mon = "Mo",
			Tue = "Di",
			Wed = "Mi",
			Thu = "Do",
			Fri = "Fr",
			Sat = "Sa",
			Sun = "So",
			-- Full
			Monday = "Montag",
			Tuesday = "Dienstag",
			Wednesday = "Mittwoch",
			Thursday = "Donnerstag",
			Friday = "Freitag",
			Saturday = "Samstag",
			Sunday = "Sonntag",
		}
	},
	-- Spanish
	["es"] = {
		Month = {
			-- Short
			Jan = "Ene",
			Feb = "Feb",
			Mar = "Mar",
			Apr = "Abr",
			May = "May",
			Jun = "Jun",
			Jul = "Jul",
			Aug = "Ago",
			Sep = "Sep",
			Oct = "Oct",
			Nov = "Nov",
			Dec = "Dic",
			-- Full
			January = "Enero",
			February = "Febrero",
			March = "Marzo",
			April = "Abril",
			-- May already defined
			June = "Junio",
			July = "Julio",
			August = "Agosto",
			September = "Septiembre",
			October = "Octubre",
			November = "Noviembre",
			December = "Diciembre",
		},
		Day = {
			-- Short
			Mon = "Lun",
			Tue = "Mar",
			Wed = "Mié",
			Thu = "Jue",
			Fri = "Vie",
			Sat = "Sáb",
			Sun = "Dom",
			-- Full
			Monday = "Lunes",
			Tuesday = "Martes",
			Wednesday = "Miércoles",
			Thursday = "Jueves",
			Friday = "Viernes",
			Saturday = "Sábado",
			Sunday = "Domingo",
		}
	},
	-- French
	["fr"] = {
		Month = {
			-- Short
			Jan = "Jan",
			Feb = "Fév",
			Mar = "Mar",
			Apr = "Avr",
			May = "Mai",
			Jun = "Juin",
			Jul = "Juil",
			Aug = "Aoû",
			Sep = "Sep",
			Oct = "Oct",
			Nov = "Nov",
			Dec = "Déc",
			-- Full
			January = "Janvier",
			February = "Février",
			March = "Mars",
			April = "Avril",
			-- May already defined
			June = "Juin",
			July = "Juillet",
			August = "Août",
			September = "Septembre",
			October = "Octobre",
			November = "Novembre",
			December = "Décembre",
		},
		Day = {
			-- Short
			Mon = "Lun",
			Tue = "Mar",
			Wed = "Mer",
			Thu = "Jeu",
			Fri = "Ven",
			Sat = "Sam",
			Sun = "Dim",
			-- Full
			Monday = "Lundi",
			Tuesday = "Mardi",
			Wednesday = "Mercredi",
			Thursday = "Jeudi",
			Friday = "Vendredi",
			Saturday = "Samedi",
			Sunday = "Dimanche",
		}
	},
	-- Italian
	["it"] = {
		Month = {
			-- Short
			Jan = "Gen",
			Feb = "Feb",
			Mar = "Mar",
			Apr = "Apr",
			May = "Mag",
			Jun = "Giu",
			Jul = "Lug",
			Aug = "Ago",
			Sep = "Set",
			Oct = "Ott",
			Nov = "Nov",
			Dec = "Dic",
			-- Full
			January = "Gennaio",
			February = "Febbraio",
			March = "Marzo",
			April = "Aprile",
			-- May already defined
			June = "Giugno",
			July = "Luglio",
			August = "Agosto",
			September = "Settembre",
			October = "Ottobre",
			November = "Novembre",
			December = "Dicembre",
		},
		Day = {
			-- Short
			Mon = "Lun",
			Tue = "Mar",
			Wed = "Mer",
			Thu = "Gio",
			Fri = "Ven",
			Sat = "Sab",
			Sun = "Dom",
			-- Full
			Monday = "Lunedì",
			Tuesday = "Martedì",
			Wednesday = "Mercoledì",
			Thursday = "Giovedì",
			Friday = "Venerdì",
			Saturday = "Sabato",
			Sunday = "Domenica",
		}
	},
	-- Japanese
	["ja"] = {
		Month = {
			-- Short
			Jan = "1月",
			Feb = "2月",
			Mar = "3月",
			Apr = "4月",
			May = "5月",
			Jun = "6月",
			Jul = "7月",
			Aug = "8月",
			Sep = "9月",
			Oct = "10月",
			Nov = "11月",
			Dec = "12月",
			-- Full
			January = "1月",
			February = "2月",
			March = "3月",
			April = "4月",
			-- May already defined
			June = "6月",
			July = "7月",
			August = "8月",
			September = "9月",
			October = "10月",
			November = "11月",
			December = "12月",
		},
		Day = {
			-- Short
			Mon = "月",
			Tue = "火",
			Wed = "水",
			Thu = "木",
			Fri = "金",
			Sat = "土",
			Sun = "日",
			-- Full
			Monday = "月曜日",
			Tuesday = "火曜日",
			Wednesday = "水曜日",
			Thursday = "木曜日",
			Friday = "金曜日",
			Saturday = "土曜日",
			Sunday = "日曜日",
		}
	},
	-- Polish
	["pl"] = {
		Month = {
			-- Short
			Jan = "Sty",
			Feb = "Lut",
			Mar = "Mar",
			Apr = "Kwi",
			May = "Maj",
			Jun = "Cze",
			Jul = "Lip",
			Aug = "Sie",
			Sep = "Wrz",
			Oct = "Paź",
			Nov = "Lis",
			Dec = "Gru",
			-- Full
			January = "Styczeń",
			February = "Luty",
			March = "Marzec",
			April = "Kwiecień",
			-- May already defined
			June = "Czerwiec",
			July = "Lipiec",
			August = "Sierpień",
			September = "Wrzesień",
			October = "Październik",
			November = "Listopad",
			December = "Grudzień",
		},
		Day = {
			-- Short
			Mon = "Pon",
			Tue = "Wto",
			Wed = "Śro",
			Thu = "Czw",
			Fri = "Pią",
			Sat = "Sob",
			Sun = "Nie",
			-- Full
			Monday = "Poniedziałek",
			Tuesday = "Wtorek",
			Wednesday = "Środa",
			Thursday = "Czwartek",
			Friday = "Piątek",
			Saturday = "Sobota",
			Sunday = "Niedziela",
		}
	},
	-- Brazilian Portuguese
	["pt-br"] = {
		Month = {
			-- Short
			Jan = "Jan",
			Feb = "Fev",
			Mar = "Mar",
			Apr = "Abr",
			May = "Mai",
			Jun = "Jun",
			Jul = "Jul",
			Aug = "Ago",
			Sep = "Set",
			Oct = "Out",
			Nov = "Nov",
			Dec = "Dez",
			-- Full
			January = "Janeiro",
			February = "Fevereiro",
			March = "Março",
			April = "Abril",
			-- May already defined
			June = "Junho",
			July = "Julho",
			August = "Agosto",
			September = "Setembro",
			October = "Outubro",
			November = "Novembro",
			December = "Dezembro",
		},
		Day = {
			-- Short
			Mon = "Seg",
			Tue = "Ter",
			Wed = "Qua",
			Thu = "Qui",
			Fri = "Sex",
			Sat = "Sáb",
			Sun = "Dom",
			-- Full
			Monday = "Segunda-feira",
			Tuesday = "Terça-feira",
			Wednesday = "Quarta-feira",
			Thursday = "Quinta-feira",
			Friday = "Sexta-feira",
			Saturday = "Sábado",
			Sunday = "Domingo",
		}
	},
	-- Portuguese
	["pt"] = {
		Month = {
			-- Short
			Jan = "Jan",
			Feb = "Fev",
			Mar = "Mar",
			Apr = "Abr",
			May = "Mai",
			Jun = "Jun",
			Jul = "Jul",
			Aug = "Ago",
			Sep = "Set",
			Oct = "Out",
			Nov = "Nov",
			Dec = "Dez",
			-- Full
			January = "Janeiro",
			February = "Fevereiro",
			March = "Março",
			April = "Abril",
			-- May already defined
			June = "Junho",
			July = "Julho",
			August = "Agosto",
			September = "Setembro",
			October = "Outubro",
			November = "Novembro",
			December = "Dezembro",
		},
		Day = {
			-- Short
			Mon = "Seg",
			Tue = "Ter",
			Wed = "Qua",
			Thu = "Qui",
			Fri = "Sex",
			Sat = "Sáb",
			Sun = "Dom",
			-- Full
			Monday = "Segunda-feira",
			Tuesday = "Terça-feira",
			Wednesday = "Quarta-feira",
			Thursday = "Quinta-feira",
			Friday = "Sexta-feira",
			Saturday = "Sábado",
			Sunday = "Domingo",
		}
	},
	-- Turkish
	["tr"] = {
		Month = {
			-- Short
			Jan = "Oca",
			Feb = "Şub",
			Mar = "Mar",
			Apr = "Nis",
			May = "May",
			Jun = "Haz",
			Jul = "Tem",
			Aug = "Ağu",
			Sep = "Eyl",
			Oct = "Eki",
			Nov = "Kas",
			Dec = "Ara",
			-- Full
			January = "Ocak",
			February = "Şubat",
			March = "Mart",
			April = "Nisan",
			-- May already defined
			June = "Haziran",
			July = "Temmuz",
			August = "Ağustos",
			September = "Eylül",
			October = "Ekim",
			November = "Kasım",
			December = "Aralık",
		},
		Day = {
			-- Short
			Mon = "Pzt",
			Tue = "Sal",
			Wed = "Çar",
			Thu = "Per",
			Fri = "Cum",
			Sat = "Cmt",
			Sun = "Paz",
			-- Full
			Monday = "Pazartesi",
			Tuesday = "Salı",
			Wednesday = "Çarşamba",
			Thursday = "Perşembe",
			Friday = "Cuma",
			Saturday = "Cumartesi",
			Sunday = "Pazar",
		}
	}
}

local current_locale = "en"

return {
	map = locale,
	-- TODO: input could already be localized, from datetime.
	-- add support to translate from localized input to another locale output.
	toLocale = function(input: string, category: string?): string
		if not category then
			return input
		end
		if category == current_locale then
			return input
		end
		local map = locale[category]
		if not map then
			return input
		end
		local collection = {map.Month, map.Day}
		return (input:gsub("%w+", function(word)
			for _, localized_words in collection do
				local localized = localized_words[word]
				if localized then
					return localized
				end
			end
			return word
		end))
	end,
}